file_format: "1"
id: dactyl
name: dactyl
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - studio
siblings:
  - dactyl_left
  - dactyl_right
